services:
  app:
    build:
      context: .
      dockerfile: dockerfile 
      target: app
    ports:
      - "80:80"
  test-runner:
    container_name: test-runner
    build:
      context: .
      dockerfile: dockerfile
      target: test-runner
  db-migrator:
    container_name: db-migrator
    build:
      context: .
      dockerfile: dockerfile
      target: db-migrator
  postgres:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
